### ISSUE TITLE
Brief question

### ISSUE THREAD

**Issue by Bui892893knm** [Menithal/ActionCameraPlugin#3]
Hey, 

sorry for asking you here but I did not find another way. 

Is it correct that LIV only supports games which game engine offers 360 degree realtime rendering? 

Could it be possible to record 360 degree gameplay by kind of using the input to LIV (VR headset output) as "video material"?

Yes, I am noob. But it would be great if you could help here. 

All the best

Andy

**Comment by Menithal** [comment]
Hey, best ask questions from the[ LIV Discord](https://discord.com/invite/liv) instead of here, this is for the plugin Im work on my free time, and I am not an Employee for LIV.

However I do know the answer for your question:
 The games in question have to have the Liv SDK integrated for LIV to work on that game.

**Comment by Bui892893knm** [comment]
Thank you.
